# -*- coding: utf-8 -*-
"""AI_career_recommendation_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQsJjApSc0iLPv9VM_wTGa0U4-6s_2m7
"""

import pandas as pd
import numpy as np

import os

os.listdir("/content")

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("career_path_in_all_field.csv")

df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.dtypes

df.nunique()

numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
categorical_columns = df.select_dtypes(include=['object']).columns

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

df.head(10)

df.sample(5)

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

df.isnull().sum()

numerical_columns = df.select_dtypes(include=np.number).columns
categorical_columns = df.select_dtypes(include="object").columns

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

for column in categorical_columns:
    print("\nColumn:", column)
    print(df[column].unique())

df.nunique()

df.info()

numerical_columns = df.select_dtypes(include=np.number).columns

print(numerical_columns)

df[numerical_columns].mean()

df[numerical_columns].median()

df[numerical_columns].mode().iloc[0]

df[numerical_columns].min()

df[numerical_columns].max()

df[numerical_columns].max() - df[numerical_columns].min()

df[numerical_columns].var()

df[numerical_columns].std()

df[numerical_columns].corr()

df[numerical_columns].describe()

import matplotlib.pyplot as plt
import seaborn as sns

df[numerical_columns].hist(figsize=(12, 8))
plt.tight_layout()
plt.show()

print(df.columns)

plt.figure(figsize=(10, 6))

df["Career"].value_counts().plot(kind="bar")

plt.title("Career Distribution")
plt.xlabel("Career")
plt.ylabel("Number of Students")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))

df["Field"].value_counts().plot(kind="bar")

plt.title("Field Distribution")
plt.xlabel("Field")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

sns.boxplot(data=df, x="Career", y="GPA")

plt.title("GPA Distribution Across Careers")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))

sns.heatmap(
    df[numerical_columns].corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

sns.pairplot(df[numerical_columns])
plt.show()

